.\" Manpage for a small prolog interpreter
.\" Contact howe.r.j.89@gmail.com to correct errors or typos.
.TH prolog 1 "VERSION" "prolog man page"
.SH NAME
prolog \- A small prolog interpreter.
.SH SYNOPSIS
.SH DESCRIPTION
.SH SEE ALSO
libprolog(3)
.SH BUGS
Probably
.SH AUTHOR
Richard James Howe (howe.r.j.89@gmail.com)
