.TH pnmfile 1 "January 2001"
.SH NAME
prffile \- describe PRF files
.SH SYNOPSIS
.B prffile
[file.prf ...]
.SH DESCRIPTION
Reads one or more
.IR prf (5)
(or
.IR mrf (5))
image files as input. Writes out short descriptions of the image type,
size, and color depth.
.SH SEE ALSO
.IR prf (5),
.IR mrf (5),
.IR pnmtoprf (1),
.IR prftopnm (1)
.SH AUTHOR
Brian Raiter
.IR <breadbox@muppetlabs.com> .
