.TH prftopnm 1 "January 2001" "Version 1.0" "Graphics Utilities"
.SH NAME
prftopnm \- convert a prf file into a portable anymap
.SH SYNOPSIS
.B prftopnm
[input.prf [output.pnm]]
.SH DESCRIPTION
Reads a
.IR prf (5)
file or a
.IR mrf (5)
file as input. Produces a portable anymap as output.
.P
.SH OPTIONS
.TP
.I -h, --help
displays online help.
.TP
.I -v, --version
displays version information.
.SH SEE ALSO
.IR pnmtoprf (1),
.IR pbm (5),
.IR pgm (5),
.IR ppm (5),
.IR prf (5),
.IR mrf (5)
.SH AUTHOR
Brian Raiter
.IR <breadbox@muppetlabs.com> .
