.\" Manpage for libprolog C API
.\" Contact howe.r.j.89@gmail.com to correct errors or typos.
.TH liblisp 3 "VERSION" "lisp library man page"
.SH NAME
libprolog \- C API for a small prolog interpreter
.SH SYNOPSIS
#include <libprolog.h>
.SH DESCRIPTION

.SH SEE ALSO
prolog(1)
.SH BUGS
Probably.
.SH AUTHOR
Richard James Howe (howe.r.j.89@gmail.com)
